services: 
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src 
    ports:
      - 8000:8000                       # 호스트 머신의 8000번 포트를 docker의 8000번 포트에 연결 
    environment:
      - WATCHFILES_FORCE_POLLING=true   # 환경에 따라 핫 리로드를 위해 필요함 
  
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Seoul'
    volumes:
      - mysql_data:/var/lib/mysql        # mysql_data라는 볼륨을 MySQL 데이터베이스 경로에 마운트
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
  
volumes:
  mysql_data:                           # 이 부분은 전역적으로 정의된 볼륨을 의미